Repository kody-sherritze/fastf1_analytics, pull requests merged in 2025-09, with the labels that each got.

#4 feat(tyre-strategy): lap count labels; filter DNS; total-laps axis; P1 at top
  .gitignore
  docs/api/gallery/index.md
  docs/assets/gallery/italian_grand_prix_2025_tyre_strategy.png
  docs/assets/gallery/monaco_2024_q_bestlaps.png
  docs/assets/gallery/monaco_grand_prix_2024_pace.png
  docs/assets/gallery/monaco_grand_prix_2024_positions.png
  docs/assets/gallery/monaco_grand_prix_2024_qual_bestlaps.png
  docs/assets/gallery/monaco_grand_prix_2024_tel_VER_LEC.png
  docs/assets/gallery/monaco_grand_prix_2024_tyre_strategy.png
  docs/gallery.md
  pyproject.toml
  src/fastf1_portfolio/charts/tyre_strategy.py
Labels: enhancement

#6 Merge Chore/update documentation
  .pre-commit-config.yaml
  README.md
  docs/gallery.md
  pyproject.toml
Labels: documentation

#12 Add cumulative time spent leading chart for 2024 season
  docs/assets/gallery/2024_drivers_time_in_first.png
  docs/assets/gallery/2024_drivers_time_in_first.yaml
  docs/gallery.md
  src/fastf1_portfolio/charts/__init__.py
  src/fastf1_portfolio/charts/time_in_first.py
  tests/test_imports.py
  tools/generate_gallery.py
  tools/plots/time_in_first.py
Labels: enhancement

#13 Update gallery documentation and source links for 2024 season charts
  docs/assets/gallery/2024_drivers_championship_points.png
  docs/assets/gallery/2024_drivers_championship_points.yaml
  docs/gallery.md
  tools/generate_gallery.py
  tools/plots/driver_championship.py
  tools/plots/drs_effectiveness.py
  tools/plots/tyre_strategy.py
Labels: enhancement

#15 Feat/tyre-performance
  README.md
  docs/assets/gallery/italian_grand_prix_2025_tyre_performance.png
  docs/assets/gallery/italian_grand_prix_2025_tyre_performance.yaml
  docs/gallery.md
  docs/reference/fastf1_analytics.md
  src/fastf1_analytics/charts/tyre_performance.py
  src/fastf1_analytics/plotting.py
  tools/plots/tyre_performance.py
Labels: documentation, enhancement

#18 Update repository references to reflect username change
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docs/gallery.md
  mkdocs.yaml
  pyproject.toml
  tools/generate_gallery.py
Labels: documentation

#19 Fix website badge URL in README to correct formatting (#19)
  README.md
Labels: bug, documentation
